export { AdminChallengesPage } from './challenges'
export { AdminOverviewPage } from './overview'
export { AdminEventPage } from './event'
export { AdminSolversPage } from './solvers'
export { AdminAdminsPage } from './admins'
export { AdminTeamsPage } from './teams'
export { AdminMonitoringPage } from './monitoring'
export { AdminUsersPage } from './users'
export { AdminLogsPage } from './logs'

